POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Video node",
  "description": "Video de nodejs",
  "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/6c1e620a-a758-4897-859d-dbee5c6dcd4d
Content-Type: application/json

{
  "title": "Video reactjs (ai meu deus)",
  "description": "Video de nodejs",
  "duration": 180
}

###

DELETE http://localhost:3333/videos/6c1e620a-a758-4897-859d-dbee5c6dcd4d